# Generated by Django 2.1.7 on 2019-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=20000)),
                ('password', models.CharField(max_length=60)),
                ('aadhar_num', models.IntegerField()),
                ('contact_num', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('permanent_address', models.TextField()),
                ('photograph_image_link', models.CharField(max_length=300)),
                ('signature_image_link', models.CharField(max_length=300)),
                ('aadhar_doc_link', models.CharField(max_length=300)),
                ('occupation', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
            ],
        ),
    ]
