# Generated by Django 2.0.13 on 2019-03-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20190326_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='occupation',
        ),
    ]
