# Generated by Django 2.1.7 on 2019-03-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_remove_voter_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='permanent_address',
            new_name='permanent_address_line_1',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='aadhar_doc_link',
        ),
        migrations.AddField(
            model_name='voter',
            name='constituency',
            field=models.CharField(default='CONSTITUENCY', max_length=200),
        ),
        migrations.AddField(
            model_name='voter',
            name='permanent_address_line_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voter',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
