# Generated by Django 2.0.1 on 2019-03-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20190328_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='date_of_birth',
        ),
    ]
