# Generated by Django 2.1.7 on 2019-03-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_remove_voter_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='photograph_image_link',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='signature_image_link',
        ),
    ]
