# Generated by Django 2.1.7 on 2019-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20190329_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\rakshit sharma\\Desktop\\profile_images'),
        ),
    ]
