# Generated by Django 2.1.7 on 2019-03-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_auto_20190331_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='aadhar_num',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='permanent_address_line_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='voter',
            name='permanent_address_line_2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
